builder:
  track: dev

labels:
  type: library
  app-group: estafette-ci
  team: estafette
  language: python

version:
  semver:
    major: 0
    minor: 3

stages:
  bake:
    image: extensions/docker:dev
    action: build
    severity: unknown
    repositories:
      - estafette
    path: .
    copy:
      - /etc/ssl/certs/ca-certificates.crt

  push-to-docker-hub:
    image: extensions/docker:dev
    action: push
    repositories:
      - estafette
    tags:
      - latest
    when: status == 'succeeded' &&
      branch == 'main'

  tag-revision:
    image: bitnami/git
    commands:
      - git tag ${ESTAFETTE_BUILD_VERSION}
      - git push origin ${ESTAFETTE_BUILD_VERSION}
    when: branch == 'main' &&
      status == 'succeeded'

  slack-notify:
    image: extensions/slack-build-status:dev
    workspace: estafette
    channels:
      - "#build-status"
    when: status == 'succeeded' ||
      status == 'failed'
